SUBBREDDIT_LIST = [
    'health',
    'medicine',
    'science',
    'Arttips',
    'cultureshare',
    'education',
    'business',
    'economy',
    'religion',
    'philosophy',
    'politics',
    'community',
    'Relax',
    'environment',
    'ecology',
    'history',
    'Archaeology',
    'Cooking',
    'literature',
    'musictheory',
    'Astronomy',
    'travel',
    'geography',
    'photography',
    'fashion',
    'FIlm',
    'psychology',
    'GYM',
    'technology',
    'Military',
    'relationships'
]

# related to max
SUPPORTED_NUMBER_OF_TOKENS = 50